def generate_html():
    # Define the HTML content
    html_content = """
    <html>
    <head>
        <title>Test HTML Page</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
        <p>This is a test HTML file generated by Python.</p>
    </body>
    </html>
    """

    # Write the HTML content to a file
    with open("test_page.html", "w") as file:
        file.write(html_content)
    
    print("HTML file 'test_page.html' generated successfully.")

if __name__ == "__main__":
    generate_html()
